### ISSUE TITLE
[CD] Attach library files to GitHub release

### ISSUE THREAD

**Issue by ViliusSutkus89** [ViliusSutkus89/tmpfile-Android#10]
```yaml
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ steps.get_version.outputs.version }}"
          name: "${{ github.event.repository.name }} v${{ steps.get_version.outputs.version }}"
          files: |
            "${{ steps.get_home_dir.outputs.home }}/.m2/repository/**"
            app-debug.apk
```
Somewhy this doesn't pick them up
